// config/entityConfig.js

const entityConfig = {
  companies: {
    title: "Companies",
    endpoint: "companies",
    buttonText: "Add Company",
    fields: [
      {
        name: "company",
        label: "Company",
        fieldType: "text",
        required: true,
        sortable: true,
      },
      {
        name: "addr1",
        label: "Address 1",
        fieldType: "text",
        required: true,
        sortable: true,
      },
      { name: "addr2", label: "Address 2", fieldType: "text", sortable: true },
      {
        name: "city",
        label: "City",
        fieldType: "text",
        required: true,
        sortable: true,
      },
      {
        name: "phone",
        label: "Phone",
        fieldType: "text",
        required: true,
        sortable: true,
      },
      { name: "fax", label: "Fax", fieldType: "text", sortable: true },
      {
        name: "email",
        label: "Email",
        fieldType: "email",
        required: true,
        sortable: true,
      },
    ],
  },

  currencies: {
    title: "Currencies",
    endpoint: "currencies",
    buttonText: "Add Currency",
    fields: [
      {
        name: "currency",
        label: "Currency",
        fieldType: "text",
        required: true,
        sortable: true,
      },
    ],
  },

  godowns: {
    title: "Godowns",
    endpoint: "godowns",
    buttonText: "Add Godown",
    fields: [
      { name: "godown", label: "Godown", fieldType: "text", required: true },
      {
        relation: "company",
        relationName: "company",
        name: "company_id",
        label: "Company",
        fieldType: "select",
        fetchFrom: "/api/setup/companies",
        optionLabelKey: "company",
        optionValueKey: "id",
        required: true,
        sortable: false,
      },
    ],
  },

  product_master_categories: {
    title: "Product Master Categories",
    endpoint: "product_master_categories",
    buttonText: "Add Product Master Category",
    fields: [
      {
        name: "pmc_name",
        label: "Product Master Category Name",
        fieldType: "text",
        required: true,
        sortable: true,
      },
    ],
  },

  product_groups: {
    title: "Product Groups",
    endpoint: "product_groups",
    buttonText: "Add Product Group",
    fields: [
      {
        name: "pg_name",
        label: "Product Group Name",
        fieldType: "text",
        required: true,
        sortable: true,
      },
      {
        relation: "ProductMasterCategories",
        relationName: "pmc_name",
        name: "pmc_id",
        label: "Product Master Category",
        fieldType: "select",
        fetchFrom: "/api/setup/product_master_categories",
        optionLabelKey: "pmc_name",
        optionValueKey: "id",
        required: true,
      },
    ],
  },

  items: {
    title: "Items",
    endpoint: "items",
    buttonText: "Add Item",
    fields: [
      {
        name: "item_name",
        label: "Item Name",
        fieldType: "text",
        required: true,
        sortable: true,
      },
      {
        relation: "item_category",
        relationName: "item_category",
        name: "ic_id",
        label: "Item Category",
        fieldType: "select",
        fetchFrom: "/api/setup/item_categories",
        optionLabelKey: "name",
        optionValueKey: "id",
        required: true,
      },
    ],
  },

  financial_years: {
    title: "Financial Years",
    endpoint: "financial_years",
    buttonText: "Add Financial Year",
    fields: [
      {
        relation: "company",
        relationName: "company",
        name: "company_id",
        label: "Company",
        fieldType: "select",
        fetchFrom: "/api/setup/companies",
        optionLabelKey: "company",
        optionValueKey: "id",
        required: true,
      },
      {
        name: "date_from",
        label: "Start Date",
        fieldType: "date",
        required: true,
        sortable: true,
      },
      {
        name: "date_to",
        label: "End Date",
        fieldType: "date",
        required: true,
        sortable: true,
      },
      {
        name: "status",
        label: "Status",
        fieldType: "select",
        options: [
          { value: "open", label: "Open" },
          { value: "closed", label: "Closed" },
        ],
        required: true,
        sortable: true,
      },
    ],
  },

  seasons: {
    title: "Seasons",
    endpoint: "seasons",
    buttonText: "Add Season",
    fields: [
      {
        relation: "company",
        relationName: "company",
        name: "company_id",
        label: "Company",
        fieldType: "select",
        fetchFrom: "/api/setup/companies",
        optionLabelKey: "company",
        optionValueKey: "id",
        required: true,
        sortable: false,
      },
      {
        name: "date_from",
        label: "Start Date",
        fieldType: "date",
        required: true,
        sortable: true,
      },
      {
        name: "date_to",
        label: "End Date",
        fieldType: "date",
        required: true,
        sortable: true,
      },
      {
        name: "status",
        label: "Status",
        fieldType: "select",
        options: [
          { value: "open", label: "Open" },
          { value: "closed", label: "Closed" },
        ],
        required: true,
        sortable: true,
      },
    ],
  },

  purchase_product_categories: {
    title: "PO Product Categories",
    endpoint: "purchase_product_categories",
    buttonText: "Add PO Product Category",
    fields: [
      {
        relation: "company",
        relationName: "company",
        name: "company_id",
        label: "Company",
        fieldType: "select",
        fetchFrom: "/api/setup/companies",
        optionLabelKey: "company",
        optionValueKey: "id",
        required: true,
        sortable: false,
      },
      {
        name: "category_name",
        label: "Category Name",
        fieldType: "text",
        required: true,
        sortable: true,
      },
    ],
  },

  delivery_modes: {
    title: "Delivery Modes",
    endpoint: "delivery_modes",
    buttonText: "Add Delivery Mode",
    fields: [
      {
        relation: "company",
        relationName: "company",
        name: "company_id",
        label: "Company",
        fieldType: "select",
        fetchFrom: "/api/setup/companies",
        optionLabelKey: "company",
        optionValueKey: "id",
        required: true,
        sortable: false,
      },
      {
        name: "delivery_mode",
        label: "Delivery Mode",
        fieldType: "text",
        required: true,
        sortable: true,
      },
      {
        name: "rate_kg",
        label: "Rate",
        fieldType: "number",
        required: true,
        sortable: true,
      },
    ],
  },

  delivery_terms: {
    title: "Delivery Terms",
    endpoint: "delivery_terms",
    buttonText: "Add Delivery Term",
    fields: [
      {
        relation: "company",
        relationName: "company",
        name: "company_id",
        label: "Company",
        fieldType: "select",
        fetchFrom: "/api/setup/companies",
        optionLabelKey: "company",
        optionValueKey: "id",
        required: true,
        sortable: false,
      },
      {
        name: "delivery_term",
        label: "Delivery Term",
        fieldType: "text",
        required: true,
        sortable: true,
      },
    ],
  },

  commission_terms: {
    title: "Commission Terms",
    endpoint: "commission_terms",
    buttonText: "Add Commission Term",
    fields: [
      {
        relation: "company",
        relationName: "company",
        name: "company_id",
        label: "Company",
        fieldType: "select",
        fetchFrom: "/api/setup/companies",
        optionLabelKey: "company",
        optionValueKey: "id",
        required: true,
        sortable: false,
      },
      {
        name: "commission_term",
        label: "Commission Term",
        fieldType: "text",
        required: true,
        sortable: true,
      },
    ],
  },

  departments: {
    title: "Departments",
    endpoint: "departments",
    buttonText: "Add Department",
    fields: [
      {
        name: "dept_name",
        label: "Dept Name",
        fieldType: "text",
        required: true,
        sortable: true,
      },
      // {
      //   relation: "company",
      //   relationName: "company",
      //   name: "company_id",
      //   label: "Company",
      //   fieldType: "select",
      //   fetchFrom: "/api/setup/companies",
      //   optionLabelKey: "company",
      //   optionValueKey: "id",
      //   required: true,
      // },
      {
        name: "dept_description",
        label: "Description",
        fieldType: "text",
        required: false,
        sortable: true,
      },
    ],
  },

  cost_centers: {
    title: "Cost Centers",
    endpoint: "cost_centers",
    buttonText: "Add Cost Center",
    fields: [
      {
        name: "ccname",
        label: "CC Name",
        fieldType: "text",
        required: true,
        sortable: true,
      },

      // {
      //   relation: "company",
      //   relationName: "company",
      //   name: "company_id",
      //   label: "Company",
      //   fieldType: "select",
      //   options: true,
      //   fetchFrom: "/api/setup/companies",
      //   optionLabelKey: "company",
      //   optionValueKey: "id",
      //   required: true,
      // },
      {
        name: "cc_description",
        label: "Description",
        fieldType: "text",
        required: false,
        sortable: true,
      },
    ],
  },

  work_locations: {
    title: "Work Locations",
    endpoint: "work_locations",
    buttonText: "Add Work Location",
    fields: [
      {
        name: "location_name",
        label: "Work Location",
        fieldType: "text",
        required: false,
        sortable: true,
      },
      {
        name: "location_description",
        label: "Description",
        fieldType: "text",
        required: false,
        sortable: true,
      },
    ],
  },

  banks: {
    title: "Banks",
    endpoint: "banks",
    buttonText: "Add Bank",
    fields: [
      {
        name: "bank_name",
        label: "Bank",
        fieldType: "text",
        required: false,
        sortable: true,
      },
      {
        name: "bank_description",
        label: "Description",
        fieldType: "text",
        required: false,
        sortable: true,
      },
    ],
  },

  job_titles: {
    title: "Job Titles",
    endpoint: "job_titles",
    buttonText: "Add Job Title",
    fields: [
      {
        name: "job_title",
        label: "Job Title",
        fieldType: "text",
        required: true,
        sortable: true,
      },
      {
        name: "job_title_description",
        label: "Description",
        fieldType: "text",
        required: true,
        sortable: true,
      },

      {
        relation: "department",
        relationName: "dept_name",
        name: "department_id",
        label: "Department",
        fieldType: "select",
        fetchFrom: "/api/setup/departments",
        optionLabelKey: "dept_name",
        optionValueKey: "id",
        required: true,
        sortable: false,
      },
    ],
  },

  allowances: {
    title: "Allowances",
    endpoint: "allowances",
    buttonText: "Add Allowance",
    fields: [
      {
        name: "allowance",
        label: "Allowance",
        fieldType: "text",
        required: true,
        sortable: true,
      },
      {
        name: "allowance_description",
        label: "Description",
        fieldType: "text",
        required: true,
        sortable: true,
      },
      {
        name: "rate",
        label: "Rate",
        fieldType: "text",
        required: true,
        sortable: true,
      },
    ],
  },

  deductions: {
    title: "Deductions",
    endpoint: "deductions",
    buttonText: "Add Deduction",
    fields: [
      {
        name: "deduction",
        label: "Deduction",
        fieldType: "text",
        required: true,
        sortable: true,
      },
      {
        name: "deduction_description",
        label: "Description",
        fieldType: "text",
        required: true,
        sortable: true,
      },
      {
        name: "rate",
        label: "Rate",
        fieldType: "text",
        required: true,
        sortable: true,
      },
    ],
  },

  leaves: {
    title: "Leaves",
    endpoint: "leaves",
    buttonText: "Add Leave",
    fields: [
      {
        name: "leave",
        label: "Leave",
        fieldType: "text",
        required: true,
        sortable: true,
      },
      {
        name: "leave_description",
        label: "Description",
        fieldType: "text",
        required: true,
        sortable: true,
      },
      {
        name: "balance",
        label: "Balance",
        fieldType: "number",
        required: false,
        sortable: true,
      },
      {
        name: "maxCarryForward",
        label: "Max Carry Forward",
        fieldType: "number",
        required: false,
        sortable: true,
      },
    ],
  },

  managers: {
    title: "Managers",
    endpoint: "managers",
    buttonText: "Add Manager",
    fields: [
      {
        name: "manager",
        label: "Manager Name",
        fieldType: "text",
        required: true,
        sortable: true,
      },
      {
        relation: "department",
        relationName: "department",
        name: "department_id",
        label: "Department",
        fieldType: "select",
        fetchFrom: "/api/setup/departments",
        optionLabelKey: "dept_name",
        optionValueKey: "id",
        required: true,
        sortable: false,
      },
      // {
      //   relation: "company",
      //   relationName: "company",
      //   name: "company_id",
      //   label: "Company",
      //   fieldType: "select",
      //   fetchFrom: "/api/setup/companies",
      //   optionLabelKey: "company",
      //   optionValueKey: "id",
      //   required: true,
      // },
    ],
  },

 employees: {
  title: "Employees",
  endpoint: "employees",
  buttonText: "Add Employee",
  tableFields: [
    { name: "firstName", label: "First Name" },
    { name: "surname", label: "Surname" },
    { name: "emailAddress", label: "Email" },
    { name: "phoneNumber", label: "Phone" },
    { name: "payType", label: "Pay Type" },
  ],
  fields: [
    {
      name: "firstName",
      label: "First Name",
      fieldType: "text",
      required: true,
    },
    {
      name: "surname",
      label: "Surname",
      fieldType: "text",
      required: true,
    },
    {
      name: "dob",
      label: "Date of Birth",
      fieldType: "date",
      required: true,
    },
    {
      name: "hireDate",
      label: "Hire Date",
      fieldType: "date",
      required: true,
    },
    {
      name: "gender",
      label: "Gender",
      fieldType: "select",
      options: ["Male", "Female", "Other"],
      // required: true,
    },
    {
      name: "phoneNumber",
      label: "Phone Number",
      fieldType: "text",
    },
    {
      name: "emailAddress",
      label: "Email",
      fieldType: "email",
      required: true,
    },
    {
      relation: "jobTitle",
      relationName: "jobTitle",
      name: "jobTitleId",
      label: "Job Title",
      fieldType: "select",
      fetchFrom: "/api/setup/job_titles",
      // required: true,
    },
    {
      relation: "department",
      relationName: "department",
      name: "departmentId",
      label: "Department",
      fieldType: "select",
      fetchFrom: "/api/setup/departments",
      // required: true,
    },
    {
      relation: "workLocation",
      relationName: "workLocation",
      name: "workLocationId",
      label: "Work Location",
      fieldType: "select",
      fetchFrom: "/api/setup/work_locations",
      // required: true,
    },
    {
      relation: "manager",
      relationName: "manager",
      name: "managerId",
      label: "Manager",
      fieldType: "select",
      fetchFrom: "/api/setup/managers",
    },
    {
      name: "status",
      label: "Status",
      fieldType: "select",
      options: ["ACTIVE", "INACTIVE"],
      // required: true,
    },
    {
      name: "paymentMethod",
      label: "Payment Method",
      fieldType: "select",
      options: ["CASH", "DIRECT_DEPOSIT", "CHEQUE"],
      // required: true,
    },
    {
      relation: "bank",
      relationName: "bank",
      name: "bankId",
      label: "Bank",
      fieldType: "select",
      fetchFrom: "/api/setup/banks",
    },
    {
      name: "accountName",
      label: "Account Name",
      fieldType: "text",
    },
    {
      name: "accountNumber",
      label: "Account Number",
      fieldType: "text",
    },
    {
      name: "payType",
      label: "Pay Type",
      fieldType: "select",
      options: ["SALARY", "HOUR"],
      // required: true,
    },
    {
      name: "rate",
      label: "Rate",
      fieldType: "number",
      required: true,
    },
    {
      name: "payFrequency",
      label: "Pay Frequency",
      fieldType: "select",
      options: ["MONTHLY", "FORTNIGHTLY", "WEEKLY"],
      // required: true,
    },
    {
      relation: "costCenter",
      relationName: "costCenter",
      name: "costCenterId",
      label: "Cost Center",
      fieldType: "select",
      fetchFrom: "/api/setup/cost_centers",
      // required: true,
    },
  ],
}

};

export default entityConfig;
