// reports/reportConfig.js
export const REPORT_CONFIG = {
  purchase: {
    title: "Purchase Report",
    description: "Detailed report of all purchase transactions",
    apiEndpoint: "/api/reports/purchase",
    filters: [
      {
        name: "dateFrom",
        label: "From Date",
        type: "date",
        required: true,
      },
      {
        name: "dateTo",
        label: "To Date",
        type: "date",
        required: true,
      },
      {
        name: "vendor",
        label: "Vendor",
        valueKey: "acno",
        type: "select",
        nameKey: "acname",
        options: "vendors",
        apiEndpoint: "/api/accounts/acno?macno=006",
        clearable: true,
      },
      {
        name: "godown",
        label: "Godown",
        nameKey: "godown",

        type: "select",
        options: "godowns",
        apiEndpoint: "/api/setup/godowns",
        clearable: true,
      },
    ],
    columns: [
      { field: "dateD", headerName: "Date", width: 120, type: "date" },
      { field: "vr_no", headerName: "Voucher No", width: 120 },
      { field: "invoice_no", headerName: "Invoice No", width: 150 },
      {
        field: "vendor_name",
        headerName: "Vendor",
        width: 200,
        valueGetter: (params) => params.row.acno?.acname || "",
      },
      {
        field: "godown_name",
        headerName: "Godown",
        width: 150,
        valueGetter: (params) => params.row.godownDetails?.godown || "",
      },
      {
        field: "total_qty",
        headerName: "Total Qty",
        width: 120,
        type: "number",
      },
      {
        field: "total_amount",
        headerName: "Total Amount",
        width: 150,
        type: "currency",
      },
    ],
    detailColumns: [
      {
        field: "item",
        headerName: "Item",
        width: 200,
        valueGetter: (params) => params.row.itemDetails?.item || "",
      },
      { field: "qty", headerName: "Qty", width: 100, type: "number" },
      { field: "rate", headerName: "Rate", width: 100, type: "currency" },
      {
        field: "gross_amount",
        headerName: "Gross Amount",
        width: 150,
        type: "currency",
      },
      { field: "st_rate", headerName: "ST Rate", width: 100, type: "number" },
      {
        field: "st_amount",
        headerName: "ST Amount",
        width: 150,
        type: "currency",
      },
      {
        field: "additional_tax",
        headerName: "Additional Tax",
        width: 150,
        type: "currency",
      },
      { field: "camt", headerName: "Amount", width: 150, type: "currency" },
    ],
    summaryFields: [
      { field: "total_qty", label: "Total Quantity", type: "number" },
      {
        field: "total_gross_amount",
        label: "Total Gross Amount",
        type: "currency",
      },
      { field: "total_tax", label: "Total Tax", type: "currency" },
      { field: "total_amount", label: "Total Net Amount", type: "currency" },
    ],
    exportOptions: {
      pdf: true,
      excel: true,
      csv: true,
    },
  },
  purchaseReturn: {
    title: "Purchase Return Report",
    description: "Detailed report of all purchase return transactions",
    apiEndpoint: "/api/reports/purchaseReturn",
    filters: [
      {
        name: "dateFrom",
        label: "From Date",
        type: "date",
        required: true,
      },
      {
        name: "dateTo",
        label: "To Date",
        type: "date",
        required: true,
      },
      {
        name: "vendor",
        nameKey: "acname",
        valueKey: "acno",
        label: "Vendor",
        type: "select",
        options: "vendors",
        apiEndpoint: "/api/accounts/acno?macno=006",
        clearable: true,
      },
      {
        name: "godown",
        nameKey: "godown",
        label: "Godown",
        type: "select",
        options: "godowns",
        apiEndpoint: "/api/setup/godowns",
        clearable: true,
      },
    ],
    columns: [
      { field: "dateD", headerName: "Date", width: 120, type: "date" },
      { field: "vr_no", headerName: "Voucher No", width: 120 },
      { field: "invoice_no", headerName: "Invoice No", width: 150 },
      {
        field: "vendor_name",
        headerName: "Vendor",
        width: 200,
        valueGetter: (params) => params.row.acno?.acname || "",
      },
      {
        field: "godown_name",
        headerName: "Godown",
        width: 150,
        valueGetter: (params) => params.row.godownDetails?.godown || "",
      },
      {
        field: "total_qty",
        headerName: "Total Qty",
        width: 120,
        type: "number",
      },
      {
        field: "total_amount",
        headerName: "Total Amount",
        width: 150,
        type: "currency",
      },
      { field: "rmk", headerName: "Narration", width: 200 },
    ],
    detailColumns: [
      {
        field: "item",
        headerName: "Item",
        width: 200,
        valueGetter: (params) => params.row.itemDetails?.item || "",
      },
      { field: "qty", headerName: "Qty", width: 100, type: "number" },
      { field: "rate", headerName: "Rate", width: 100, type: "currency" },
      {
        field: "gross_amount",
        headerName: "Gross Amount",
        width: 150,
        type: "currency",
      },
      { field: "st_rate", headerName: "ST Rate", width: 100, type: "number" },
      {
        field: "st_amount",
        headerName: "ST Amount",
        width: 150,
        type: "currency",
      },
      {
        field: "additional_tax",
        headerName: "Additional Tax",
        width: 150,
        type: "currency",
      },
      { field: "amount", headerName: "Amount", width: 150, type: "currency" },
    ],
    summaryFields: [
      { field: "total_qty", label: "Total Quantity", type: "number" },
      {
        field: "total_gross_amount",
        label: "Total Gross Amount",
        type: "currency",
      },
      { field: "total_tax", label: "Total Tax", type: "currency" },
      { field: "total_amount", label: "Total Net Amount", type: "currency" },
    ],
    exportOptions: {
      pdf: true,
      excel: true,
      csv: true,
    },
  },
  sale: {
    title: "Sales Report",
    description: "Detailed report of all sales transactions",
    apiEndpoint: "/api/reports/sale",
    filters: [
      {
        name: "dateFrom",
        label: "From Date",
        type: "date",
        required: true,
      },
      {
        name: "dateTo",
        label: "To Date",
        type: "date",
        required: true,
      },
      {
        name: "customer",
        label: "Customer",
        type: "select",
        nameKey: "acname",
        valueKey: "acno",
        options: "customers",
        apiEndpoint: "/api/accounts/acno?macno=001",
        clearable: true,
      },
      {
        name: "godown",
        label: "Godown",
        nameKey: "godown",
        type: "select",
        options: "godowns",
        apiEndpoint: "/api/setup/godowns",
        clearable: true,
      },
    ],
    columns: [
      { field: "dateD", headerName: "Date", width: 120, type: "date" },
      { field: "vr_no", headerName: "Voucher No", width: 120 },
      { field: "invoice_no", headerName: "Invoice No", width: 150 },
      {
        field: "customer_name",
        headerName: "Customer",
        width: 200,
        valueGetter: (params) => params.row.acno?.acname || "",
      },
      {
        field: "godown_name",
        headerName: "Godown",
        width: 150,
        valueGetter: (params) => params.row.godownDetails?.godown || "",
      },
      {
        field: "total_qty",
        headerName: "Total Qty",
        width: 120,
        type: "number",
      },
      {
        field: "total_amount",
        headerName: "Total Amount",
        width: 150,
        type: "currency",
      },
      { field: "rmk", headerName: "Narration", width: 200 },
    ],
    detailColumns: [
      {
        field: "item",
        headerName: "Item",
        width: 200,
        valueGetter: (params) => params.row.itemDetails?.item || "",
      },
      { field: "qty", headerName: "Qty", width: 100, type: "number" },
      { field: "rate", headerName: "Rate", width: 100, type: "currency" },
      {
        field: "gross_amount",
        headerName: "Gross Amount",
        width: 150,
        type: "currency",
      },
      { field: "st_rate", headerName: "ST Rate", width: 100, type: "number" },
      {
        field: "st_amount",
        headerName: "ST Amount",
        width: 150,
        type: "currency",
      },
      {
        field: "additional_tax",
        headerName: "Additional Tax",
        width: 150,
        type: "currency",
      },
      { field: "amount", headerName: "Amount", width: 150, type: "currency" },
    ],
    summaryFields: [
      { field: "total_qty", label: "Total Quantity", type: "number" },
      {
        field: "total_gross_amount",
        label: "Total Gross Amount",
        type: "currency",
      },
      { field: "total_tax", label: "Total Tax", type: "currency" },
      { field: "total_amount", label: "Total Net Amount", type: "currency" },
    ],
    exportOptions: {
      pdf: true,
      excel: true,
      csv: true,
    },
  },
  payment: {
    title: "Payment Report",
    description: "Detailed report of all payment transactions",
    apiEndpoint: "/api/reports/payment",
    filters: [
      { name: "dateFrom", label: "From Date", type: "date", required: true },
      { name: "dateTo", label: "To Date", type: "date", required: true },
      {
        name: "paidfrom",
        label: "Paid From",
        type: "select",
        nameKey: "acname",
        valueKey: "acno",
        options: "vendors",
        apiEndpoint: "/api/accounts/acno?macno=003,004",
        clearable: true,
      },
    ],
    columns: [
      { field: "date", headerName: "Date", width: 120, type: "date" },
      { field: "vr_no", headerName: "Voucher No", width: 120 },
      {
        field: "account",
        headerName: "Paid From",
        width: 200,
        // valueGetter: (params) => params.row.acno?.acname || "",
      },
      { field: "amount", headerName: "Amount", width: 150, type: "currency"
       },
      { field: "narration", headerName: "Remarks", width: 200 },
    ],
    summaryFields: [
      { field: "total_transactions", label: "Total Transactions", type: "number" },
      { field: "total_net", label: "Total Net Amount", type: "currency" },
    ],
    exportOptions: { pdf: true, excel: true, csv: true },
  },
  receipt: {
    title: "Receipt Report",
    description: "Detailed report of all receipt transactions",
    apiEndpoint: "/api/reports/receipt",
    filters: [
      { name: "dateFrom", label: "From Date", type: "date", required: true },
      { name: "dateTo", label: "To Date", type: "date", required: true },
      {
        name: "receivedat",
        label: "Recieved At",
        type: "select",
        nameKey: "acname",
        valueKey: "acno",
        options: "customers",
        apiEndpoint: "/api/accounts/acno?macno=003,004",
        clearable: true,
      },
    ],
    columns: [
      { field: "date", headerName: "Date", width: 120, type: "date" },
      { field: "vr_no", headerName: "Voucher No", width: 120 },
      {
        field: "account",
        headerName: "Received At",
        width: 200,
        // valueGetter: (params) => params.row.acno?.acname || "",
      },
      { field: "amount", headerName: "Amount", width: 150, type: "currency" },
      { field: "narration", headerName: "Remarks", width: 200 },
    ],
    summaryFields: [
      { field: "total_transactions", label: "Total Transactions", type: "number" },
      { field: "total_net", label: "Total Net Amount", type: "currency" },
    ],
    exportOptions: { pdf: true, excel: true, csv: true },
  },
  journal: {
    title: "Journal Voucher Report",
    description: "Detailed report of all journal vouchers",
    apiEndpoint: "/api/reports/journal",
    filters: [
      { name: "dateFrom", label: "From Date", type: "date", required: true },
      { name: "dateTo", label: "To Date", type: "date", required: true },
    ],
    columns: [
      { field: "date", headerName: "Date", width: 120, type: "date" },
      { field: "vr_no", headerName: "Voucher No", width: 120 },
      { field: "damt", headerName: "Debit", width: 150, type: "currency" },
      { field: "camt", headerName: "Credit", width: 150, type: "currency" },
      { field: "narration", headerName: "Narration", width: 200 },
    ],
    summaryFields: [
      { field: "total_transactions", label: "Total Transactions", type: "number" },
      { field: "total_damt", label: "Total Debit", type: "currency" },
      { field: "total_camt", label: "Total Credit", type: "currency" },

    ],
    exportOptions: { pdf: true, excel: true, csv: true },
  },
  saleReturn: {
    title: "Sales Return Report",
    description: "Detailed report of all sales return transactions",
    apiEndpoint: "/api/reports/saleReturn",
    filters: [
      {
        name: "dateFrom",
        label: "From Date",
        type: "date",
        required: true,
      },
      {
        name: "dateTo",
        label: "To Date",
        type: "date",
        required: true,
      },
      {
        name: "customer",
        label: "Customer",
        type: "select",
        nameKey: "acname",
        valueKey: "acno",
        options: "customers",
        apiEndpoint: "/api/accounts/acno?macno=001",
        clearable: true,
      },
      {
        name: "godown",
        label: "Godown",
        type: "select",
        nameKey: "godown",
        options: "godowns",
        apiEndpoint: "/api/setup/godowns",
        clearable: true,
      },
    ],
    columns: [
      { field: "dateD", headerName: "Date", width: 120, type: "date" },
      { field: "vr_no", headerName: "Voucher No", width: 120 },
      { field: "invoice_no", headerName: "Invoice No", width: 150 },
      {
        field: "customer_name",
        headerName: "Customer",
        width: 200,
        valueGetter: (params) => params.row.acno?.acname || "",
      },
      {
        field: "godown_name",
        headerName: "Godown",
        width: 150,
        valueGetter: (params) => params.row.godownDetails?.godown || "",
      },
      {
        field: "total_qty",
        headerName: "Total Qty",
        width: 120,
        type: "number",
      },
      {
        field: "total_amount",
        headerName: "Total Amount",
        width: 150,
        type: "currency",
      },
      { field: "rmk", headerName: "Narration", width: 200 },
    ],
    detailColumns: [
      {
        field: "item",
        headerName: "Item",
        width: 200,
        valueGetter: (params) => params.row.itemDetails?.item || "",
      },
      { field: "qty", headerName: "Qty", width: 100, type: "number" },
      { field: "rate", headerName: "Rate", width: 100, type: "currency" },
      {
        field: "gross_amount",
        headerName: "Gross Amount",
        width: 150,
        type: "currency",
      },
      { field: "st_rate", headerName: "ST Rate", width: 100, type: "number" },
      {
        field: "st_amount",
        headerName: "ST Amount",
        width: 150,
        type: "currency",
      },
      {
        field: "additional_tax",
        headerName: "Additional Tax",
        width: 150,
        type: "currency",
      },
      { field: "amount", headerName: "Amount", width: 150, type: "currency" },
    ],
    summaryFields: [
      { field: "total_qty", label: "Total Quantity", type: "number" },
      {
        field: "total_gross_amount",
        label: "Total Gross Amount",
        type: "currency",
      },
      { field: "total_tax", label: "Total Tax", type: "currency" },
      { field: "total_amount", label: "Total Net Amount", type: "currency" },
    ],
    exportOptions: {
      pdf: true,
      excel: true,
      csv: true,
    },
  },
  stock: {
    title: "Stock Report",
    description: "Current stock levels for all items",
    apiEndpoint: "/api/reports/stock",
    filters: [
      {
        name: "category",
        label: "Category",
        nameKey: "ic_name",
        type: "select",
        options: "itemCategories",
        apiEndpoint: "/api/setup/item_categories",
        clearable: true,
      },
      {
        name: "showZero",
        label: "Show Zero Stock",
        type: "checkbox",
        default: false,
      },
    ],
    columns: [
      { field: "item", headerName: "Item", width: 250 },
      { field: "sku", headerName: "SKU", width: 150 },
      {
        field: "category",
        headerName: "Category",
        width: 200,
        valueGetter: (params) => params.row.itemCategories?.ic_name || "",
      },
      {
        field: "stock",
        headerName: "Current Stock",
        width: 150,
        type: "number",
      },
      { field: "price", headerName: "Price", width: 120, type: "currency" },
      {
        field: "value",
        headerName: "Stock Value",
        width: 150,
        type: "currency",
        valueGetter: (params) =>
          (params.row.stock || 0) * (params.row.price || 0),
      },
    ],
    summaryFields: [
      { field: "total_items", label: "Total Items", type: "number" },
      { field: "total_stock", label: "Total Stock", type: "number" },
      { field: "total_value", label: "Total Stock Value", type: "currency" },
    ],
    exportOptions: {
      pdf: true,
      excel: true,
      csv: true,
    },
  },
  stockActivity: {
    title: "Stock Activity Report",
    description: "Product-wise stock movement analysis",
    apiEndpoint: "/api/reports/stockActivity",
    filters: [
      {
        name: "dateFrom",
        label: "From Date",
        type: "date",
        required: true,
      },
      {
        name: "dateTo",
        label: "To Date",
        type: "date",
        required: true,
      },
      {
        name: "product",
        label: "Product",
        type: "select",
        options: "products",
        apiEndpoint: "/api/setup/items",
        valueKey: "itcd",
        nameKey: "item",
        clearable: true,
      },
      {
        name: "category",
        label: "Category",
        type: "select",
        options: "itemCategories",
        apiEndpoint: "/api/setup/item_categories",
        nameKey: "ic_name",
        clearable: true,
      },
    ],
    columns: [
      { field: "product_code", headerName: "Product Code", width: 120 },
      { field: "product_name", headerName: "Product Name", width: 200 },
      { field: "category", headerName: "Category", width: 150 },
      {
        field: "opening_stock",
        headerName: "OPENING STOCK",
        width: 120,
        type: "number",
      },
      {
        field: "purchase_qty",
        headerName: "PURCHASE QTY",
        width: 120,
        type: "number",
      },
      {
        field: "purchase_ret_qty",
        headerName: "PURCAHSE RET QTY",
        width: 140,
        type: "number",
      },
      {
        field: "total_qty",
        headerName: "TOTAL QTY",
        width: 120,
        type: "number",
      },
      { field: "sale_qty", headerName: "SALE QTY", width: 120, type: "number" },
      {
        field: "sale_ret_qty",
        headerName: "SALE RET QTY",
        width: 140,
        type: "number",
      },
      { field: "pos_qty", headerName: "POS QTY", width: 120, type: "number" },
      {
        field: "stock_balance",
        headerName: "STOCK BALANCE",
        width: 140,
        type: "number",
      },
    ],
    exportOptions: {
      pdf: true,
      excel: true,
      csv: true,
    },
  },
  tradingMargin: {
    title: "Trading Margin Report",
    description:
      "Profitability analysis by item (Purchase, Sales, Returns, POS)",
    apiEndpoint: "/api/reports/tradingMargin",
    filters: [
      {
        name: "dateFrom",
        label: "From Date",
        type: "date",
        required: true,
      },
      {
        name: "dateTo",
        label: "To Date",
        type: "date",
        required: true,
      },
      {
        name: "item",
        valueKey: "itcd",
        nameKey: "item",
        label: "Item",
        type: "select",
        options: "items",
        apiEndpoint: "/api/setup/items",
        clearable: true,
      },
      {
        name: "category",
        label: "Category",
        nameKey: "ic_name",
        type: "select",
        options: "itemCategories",
        apiEndpoint: "/api/setup/item_categories",
        clearable: true,
      },
    ],
    columns: [
      {
        field: "item",
        headerName: "Item",
        width: 250,
        valueGetter: (params) => params.row.itemDetails?.item || "",
      },
      {
        field: "category",
        headerName: "Category",
        width: 200,
        valueGetter: (params) =>
          params.row.itemDetails?.itemCategories?.ic_name || "",
      },

      // --- Purchases ---
      {
        field: "purchase_qty",
        headerName: "Purchase Qty",
        width: 130,
        type: "number",
      },
      {
        field: "purchase_amount",
        headerName: "Purchase Amount",
        width: 150,
        type: "currency",
      },
      {
        field: "purchase_return_qty",
        headerName: "Purchase Return Qty",
        width: 160,
        type: "number",
      },
      {
        field: "purchase_return_amount",
        headerName: "Purchase Return Amt",
        width: 170,
        type: "currency",
      },

      // --- Sales ---
      { field: "sale_qty", headerName: "Sale Qty", width: 120, type: "number" },
      {
        field: "sale_amount",
        headerName: "Sale Amount",
        width: 150,
        type: "currency",
      },
      {
        field: "sale_return_qty",
        headerName: "Sale Return Qty",
        width: 150,
        type: "number",
      },
      {
        field: "sale_return_amount",
        headerName: "Sale Return Amt",
        width: 160,
        type: "currency",
      },

      // --- POS ---
      { field: "pos_qty", headerName: "POS Qty", width: 110, type: "number" },
      {
        field: "pos_amount",
        headerName: "POS Amount",
        width: 140,
        type: "currency",
      },

      // --- Averages and Margins ---
      {
        field: "avg_purchase_rate",
        headerName: "Avg Purchase Rate",
        width: 150,
        type: "currency",
      },
      {
        field: "avg_sale_rate",
        headerName: "Avg Sale Rate",
        width: 150,
        type: "currency",
      },
      { field: "margin", headerName: "Margin", width: 120, type: "currency" },
      {
        field: "margin_percent",
        headerName: "Margin %",
        width: 120,
        type: "percent",
      },
    ],
    summaryFields: [
      {
        field: "total_purchase_qty",
        label: "Total Purchase Qty",
        type: "number",
      },
      {
        field: "total_purchase_amount",
        label: "Total Purchase Amount",
        type: "currency",
      },
      {
        field: "total_purchase_return_qty",
        label: "Total Purchase Return Qty",
        type: "number",
      },
      {
        field: "total_purchase_return_amount",
        label: "Total Purchase Return Amt",
        type: "currency",
      },

      { field: "total_sale_qty", label: "Total Sale Qty", type: "number" },
      {
        field: "total_sale_amount",
        label: "Total Sale Amount",
        type: "currency",
      },
      {
        field: "total_sale_return_qty",
        label: "Total Sale Return Qty",
        type: "number",
      },
      {
        field: "total_sale_return_amount",
        label: "Total Sale Return Amt",
        type: "currency",
      },

      { field: "total_pos_qty", label: "Total POS Qty", type: "number" },
      {
        field: "total_pos_amount",
        label: "Total POS Amount",
        type: "currency",
      },

      { field: "total_margin", label: "Total Margin", type: "currency" },
      { field: "avg_margin_percent", label: "Avg Margin %", type: "percent" },
    ],
    exportOptions: {
      pdf: true,
      excel: true,
      csv: true,
    },
  },
  stockLedger: {
    title: "Stock Ledger Report",
    description: "Detailed movement of stock items over time",
    apiEndpoint: "/api/reports/stockLedger",
    filters: [
      {
        name: "dateFrom",
        label: "From Date",
        type: "date",
        required: true,
      },
      {
        name: "dateTo",
        label: "To Date",
        type: "date",
        required: true,
      },
      {
        name: "item",
        label: "Item",
        type: "select",
        nameKey: "item",
        valueKey: "itcd",
        options: "items",
        apiEndpoint: "/api/setup/items",
        required: true,
      },
      {
        name: "godown",
        label: "Godown",
        type: "select",
        nameKey: "godown",
        options: "godowns",
        apiEndpoint: "/api/setup/godowns",
        clearable: true,
      },
    ],
    columns: [
      { field: "date", headerName: "Date", width: 120, type: "date" },
      { field: "transaction_no", headerName: "Trans No", width: 120 },
      { field: "transaction_type", headerName: "Trans Type", width: 150 },
      { field: "vendor_customer", headerName: "Vendor/Customer", width: 200 },
      {
        field: "opening_qty",
        headerName: "Qty Opening",
        width: 120,
        type: "number",
      },
      { field: "qty_in", headerName: "Qty In", width: 100, type: "number" },
      { field: "qty_out", headerName: "Qty Out", width: 100, type: "number" },
      {
        field: "closing_qty",
        headerName: "Qty Closing",
        width: 120,
        type: "number",
      },
    ],
    summaryFields: [
      { field: "total_in", label: "Total In", type: "number" },
      { field: "total_out", label: "Total Out", type: "number" },
      { field: "net_movement", label: "Net Movement", type: "number" },
    ],
    exportOptions: {
      pdf: true,
      excel: true,
      csv: true,
    },
  },
  posTransactions: {
    title: "POS Transactions Report",
    description: "Detailed report of all Point of Sale transactions",
    apiEndpoint: "/api/reports/posTransactions",
    filters: [
      {
        name: "dateFrom",
        label: "From Date",
        type: "date",
        required: true,
      },
      {
        name: "dateTo",
        label: "To Date",
        type: "date",
        required: true,
      },
      {
        name: "customer",
        label: "Customer",
        type: "select",
        nameKey: "acname",
        valueKey: "acno",
        options: "customers",
        apiEndpoint: "/api/accounts/acno?macno=001",
        clearable: true,
      },
      {
        name: "paymentMode",
        label: "Payment Mode",
        type: "select",
        options: [
          { value: "all", label: "All" },
          { value: "cash", label: "Cash" },
          { value: "card", label: "Card" },
          { value: "upi", label: "UPI" },
          { value: "credit", label: "Credit" },
        ],
        default: "all",
      },
    ],
    columns: [
      { field: "dateD", headerName: "Date", width: 120, type: "date" },
      { field: "vr_no", headerName: "Voucher No", width: 120 },
      { field: "invoice_no", headerName: "Invoice No", width: 150 },
      {
        field: "customer_name",
        headerName: "Customer",
        width: 200,
        valueGetter: (params) => params.row.acno?.acname || "Walk-in Customer",
      },
      { field: "payment_mode", headerName: "Payment Mode", width: 120 },
      {
        field: "total_qty",
        headerName: "Total Qty",
        width: 120,
        type: "number",
      },
      {
        field: "total_amount",
        headerName: "Total Amount",
        width: 150,
        type: "currency",
      },
      {
        field: "discount",
        headerName: "Discount",
        width: 120,
        type: "currency",
      },
      {
        field: "net_amount",
        headerName: "Net Amount",
        width: 150,
        type: "currency",
      },
    ],
    detailColumns: [
      {
        field: "item",
        headerName: "Item",
        width: 200,
        valueGetter: (params) => params.row.itemDetails?.item || "",
      },
      { field: "qty", headerName: "Qty", width: 100, type: "number" },
      { field: "rate", headerName: "Rate", width: 100, type: "currency" },
      {
        field: "gross_amount",
        headerName: "Amount",
        width: 150,
        type: "currency",
      },
      {
        field: "discount",
        headerName: "Line Discount",
        width: 150,
        type: "currency",
      },
    ],
    summaryFields: [
      {
        field: "total_transactions",
        label: "Total Transactions",
        type: "number",
      },
      { field: "total_qty", label: "Total Quantity", type: "number" },
      { field: "total_amount", label: "Total Amount", type: "currency" },
      { field: "total_discount", label: "Total Discount", type: "currency" },
      {
        field: "total_net_amount",
        label: "Total Net Amount",
        type: "currency",
      },
    ],
    exportOptions: {
      pdf: true,
      excel: true,
      csv: true,
    },
  },
  accountLedger: {
    title: "Account Ledger",
    description: "Detailed ledger entries for a specific account showing running balance",
    apiEndpoint: "/api/reports/accountLedger",
    filters: [
      { name: "dateFrom", label: "From Date", type: "date", required: true },
      { name: "dateTo", label: "To Date", type: "date", required: true },
      {
        name: "account",
        label: "Account",
        type: "select",
        nameKey: "acname",
        valueKey: "acno",
        options: "accounts",
        apiEndpoint: "/api/accounts/acno?excludeMacno=003,004",
        required: true,
      },
    ],
    columns: [
      { field: "date", headerName: "Date", width: 120, type: "date" },
      { field: "vr_no", headerName: "Voucher No", width: 120 },
      { field: "tran_type", headerName: "Type", width: 200 },
      { field: "narration", headerName: "Narration", width: 200 },
      { field: "debit", headerName: "Debit", width: 150, type: "currency" },
      { field: "credit", headerName: "Credit", width: 150, type: "currency" },
      { field: "balance", headerName: "Balance", width: 150, type: "currency" },
    ],
    exportOptions: { pdf: true, excel: true, csv: true },
  },

  accountsActivity: {
    title: "Accounts Activity Report",
    description: "Summarized activity for all accounts showing opening, transactions, and closing",
    apiEndpoint: "/api/reports/accountsActivity",
    filters: [
      { name: "dateFrom", label: "From Date", type: "date", required: true },
      { name: "dateTo", label: "To Date", type: "date", required: true },
    ],
    columns: [
      { field: "account", headerName: "Account", width: 200 },
      { field: "opening_balance", headerName: "Opening Balance", width: 150, type: "currency" },
      { field: "debit", headerName: "Debit", width: 150, type: "currency" },
      { field: "credit", headerName: "Credit", width: 150, type: "currency" },
      { field: "closing_balance", headerName: "Closing Balance", width: 150, type: "currency" },
    ],
    exportOptions: { pdf: true, excel: true, csv: true },
  },

  trialBalance: {
    title: "Trial Balance",
    description: "A summary of all ledger accounts with debit and credit totals to verify ledger integrity",
    apiEndpoint: "/api/reports/trialBalance",
    filters: [
      { name: "dateTo", label: "As of Date", type: "date", required: true },
    ],
    columns: [
      { field: "account", headerName: "Account", width: 200 },
      { field: "debit", headerName: "Debit", width: 150, type: "currency" },
      { field: "credit", headerName: "Credit", width: 150, type: "currency" },
      { field: "balance", headerName: "Balance", width: 150, type: "currency" },
    ],
    exportOptions: { pdf: true, excel: true, csv: true },
  },

};
