export const VOUCHER_CONFIG = {
  payment: {
    tran_code: 2,
    hasDeductionBlock: true,
    masterFields: [
      { name: "dateD", label: "Date", type: "date", required: true },
      { name: "time", label: "Time", type: "time", required: true },
      {
        name: "pycd",
        formName: "pycd",
        label: "Paid From",
        type: "select",
        options: "accounts",
        apiEndpoint: "/api/accounts/acno?macno=001",
        createEndpoint: "/api/accounts/acno",
        nameKey: "acname",
        valueKey: "acno",
        required: true,
        modalFields: [
          { name: "acname", label: "Account Name", type: "text", required: true },
          {
            name: "acno",
            label: "Main Account",
            type: "select",
            options: "mainAccounts",
            apiEndpoint: "/api/accounts/acno?macno=001",
            valueKey: "acno",
            nameKey: "acname",
            required: true,
          },
        ],
      },
      { name: "vr_no", label: "Vr No", type: "text", required: true, autoGenerate: true },
      { name: "check_no", label: "Check No", type: "text" },
      { name: "check_date", label: "Check Date", type: "date" },
      { name: "rmk", label: "Narration", type: "textarea" },
      { name: "rmk1", label: "Export Inv From", type: "text" },
      { name: "rmk2", label: "RMK1", type: "text" },
      { name: "rmk3", label: "Fwd Cont#", type: "text" },
      { name: "rmk4", label: "FE Ref#", type: "text" },
      { name: "rmk5", label: "RMK5", type: "text" },
    ],
    lineFields: [
      {
        name: "acname",
        formName: "acno",
        label: "A/c Name",
        type: "select",
        options: "accounts",
        apiEndpoint: "/api/accounts/acno?macno=001",
        createEndpoint: "/api/accounts/acno",
        nameKey: "acname",
        valueKey: "acno",
        modalFields: [
          { name: "acname", label: "Account Name", type: "text", required: true },
          {
            name: "macno",
            label: "Main Account",
            type: "select",
            options: "mainAccounts",
            apiEndpoint: "/api/accounts/macno",
            valueKey: "macno",
            nameKey: "macname",
            required: true,
          },
        ],
      },
      {
        name: "ccname",
        formName: "ccno",
        label: "Cost Center",
        type: "select",
        options: "costCenters",
        apiEndpoint: "/api/setup/cost_centers",
        createEndpoint: "/api/setup/cost_centers",
        nameKey: "ccname",
        valueKey: "ccno",
        modalFields: [
          { name: "ccname", label: "Cost Center Name", type: "text", required: true },
        ],
      },
      { name: "invoice_no", label: "Invoice No", type: "text" },
      { name: "wht_rate", label: "WHT Rate", type: "number" },
      { name: "chno", label: "Check No", type: "text" },
      { name: "narration1", label: "Narration", type: "text" },
      { name: "narration2", label: "Narration2", type: "text" },
      {
        name: "currency",
        formName: "currency",
        label: "Currency",
        type: "select",
        options: "currencies",
        apiEndpoint: "/api/setup/currencies",
        createEndpoint: "/api/setup/currencies",
        nameKey: "currency",
        valueKey: "id",
        modalFields: [
          { name: "currency", label: "Currency Name", type: "text", required: true },
        ],
      },
      { name: "fc_amount", label: "FC Amt", type: "number" },
      { name: "rate", label: "Exc Rate", type: "number" },
      {
        name: "damt",
        label: "Amount",
        type: "number",
        dependencies: ["fc_amount", "rate"],
        calculate: (v) => v.fc_amount * v.rate,
      },
    ],
    deductionFields: [
      {
        name: "acname",
        formName: "acno",
        label: "A/c Name",
        type: "select",
        options: "accounts",
        apiEndpoint: "/api/accounts/acno?macno=001",
        createEndpoint: "/api/accounts/acno",
        nameKey: "acname",
        valueKey: "acno",
        modalFields: [
          { name: "acname", label: "Account Name", type: "text", required: true },
          {
            name: "macno",
            label: "Main Account",
            type: "select",
            options: "mainAccounts",
            apiEndpoint: "/api/accounts/macno",
            valueKey: "macno",
            nameKey: "macname",
            required: true,
          },
        ],
      },
      {
        name: "ccname",
        formName: "ccno",
        label: "Cost Center",
        type: "select",
        options: "costCenters",
        apiEndpoint: "/api/setup/cost_centers",
        createEndpoint: "/api/setup/cost_centers",
        nameKey: "ccname",
        valueKey: "ccno",
        modalFields: [
          { name: "ccname", label: "Cost Center Name", type: "text", required: true },
        ],
      },
      { name: "invoice_no", label: "Invoice No", type: "text" },
      { name: "wht_rate", label: "WHT Rate", type: "number" },
      { name: "chno", label: "Check No", type: "text" },
      { name: "narration1", label: "Narration", type: "text" },
      { name: "narration2", label: "Narration2", type: "text" },
      {
        name: "currency",
        formName: "currency",
        label: "Currency",
        type: "select",
        options: "currencies",
        apiEndpoint: "/api/setup/currencies",
        createEndpoint: "/api/setup/currencies",
        nameKey: "currency",
        valueKey: "id",
        modalFields: [
          { name: "currency", label: "Currency Name", type: "text", required: true },
        ],
      },
      { name: "fc_amount", label: "FC Amt", type: "number" },
      { name: "rate", label: "Exc Rate", type: "number" },
      {
        name: "camt",
        label: "Amount",
        type: "number",
        dependencies: ["fc_amount", "rate"],
        calculate: (v) => v.fc_amount * v.rate,
      },
    ],
    totals: {
      mainTotal: {
        label: "Total Payments",
        calculate: (lines) => lines.reduce((sum, l) => sum + (l.damt || 0), 0),
      },
      deductionTotal: {
        label: "Total Deductions",
        calculate: (lines) => lines.reduce((sum, l) => sum + (l.camt || 0), 0),
      },
      netTotal: {
        label: "Net Payment",
        calculate: (_, t) => t.mainTotal - t.deductionTotal,
      },
    },
    balanceCheck: {
      condition: (formData) => formData.totals.netTotal >= 0,
      errorMessage: (formData) =>
        `Net Payment (${formData.totals.netTotal.toFixed(2)}) cannot be negative.`,
    },
    tableFields: [
      { name: "dateD", label: "Date", type: "date" },
      { name: "tran_id", label: "Transaction No", type: "text" },
      { name: "vr_no", label: "Voucher No", type: "text" },
      { name: "pycd", label: "Paid From", type: "text", refApi: "/api/accounts/acno?acno=", refValueKey: "acno",refNameKey: "acname",  },
      { name: "rmk", label: "Narration", type: "text" },
    ],
  },
  receipt: {
    tran_code: 1,
    hasDeductionBlock: true,
    masterFields: [
      { name: "dateD", label: "Date", type: "date", required: true },
      { name: "time", label: "Time", type: "time", required: true },
      {
        name: "pycd",
        formName: "pycd",
        label: "Received At",
        type: "select",
        options: "accounts",
        apiEndpoint: "/api/accounts/acno?macno=001",
        createEndpoint: "/api/accounts/acno",
        nameKey: "acname",
        valueKey: "acno",
        required: true,
        modalFields: [
          { name: "acname", label: "Account Name", type: "text", required: true },
          {
            name: "macno",
            label: "Main Account",
            type: "select",
            options: "mainAccounts",
            apiEndpoint: "/api/accounts/macno",
            valueKey: "macno",
            nameKey: "macname",
            required: true,
          },
        ],
      },
      { name: "vr_no", label: "Vr No", type: "text", required: true, autoGenerate: true },
      { name: "check_no", label: "Check No", type: "text" },
      { name: "check_date", label: "Check Date", type: "date" },
      { name: "rmk", label: "Narration", type: "textarea" },
      { name: "rmk1", label: "Exp Basis", type: "text" },
      { name: "rmk2", label: "Export INV#", type: "text" },
      { name: "rmk3", label: "Fwd Cont#", type: "text" },
      { name: "rmk5", label: "FE Ref#", type: "text" },
    ],
    lineFields: [
      {
        name: "acname",
        formName: "acno",
        label: "A/c Name",
        type: "select",
        options: "accounts",
        apiEndpoint: "/api/accounts/acno?macno=001",
        createEndpoint: "/api/accounts/acno",
        nameKey: "acname",
        valueKey: "acno",
        modalFields: [
          { name: "acname", label: "Account Name", type: "text", required: true },
          {
            name: "macno",
            label: "Main Account",
            type: "select",
            options: "mainAccounts",
            apiEndpoint: "/api/accounts/macno",
            valueKey: "macno",
            nameKey: "macname",
            required: true,
          },
        ],
      },
      {
        name: "ccname",
        formName: "ccno",
        label: "Cost Center",
        type: "select",
        options: "costCenters",
        apiEndpoint: "/api/setup/cost_centers",
        createEndpoint: "/api/setup/cost_centers",
        nameKey: "ccname",
        valueKey: "ccno",
        modalFields: [
          { name: "ccname", label: "Cost Center Name", type: "text", required: true },
        ],
      },
      { name: "invoice_no", label: "Invoice No", type: "text" },
      { name: "wht_rate", label: "WHT Rate", type: "number" },
      { name: "chno", label: "Check No", type: "text" },
      { name: "narration1", label: "Narration", type: "text" },
      { name: "narration2", label: "Narration2", type: "text" },
      {
        name: "currency",
        formName: "currency",
        label: "Currency",
        type: "select",
        options: "currencies",
        apiEndpoint: "/api/setup/currencies",
        createEndpoint: "/api/setup/currencies",
        nameKey: "currency",
        valueKey: "id",
        modalFields: [
          { name: "currency", label: "Currency Name", type: "text", required: true },
        ],
      },
      { name: "fc_amount", label: "FC Amt", type: "number" },
      { name: "rate", label: "Exc Rate", type: "number" },
      {
        name: "camt",
        label: "Amount",
        type: "number",
        dependencies: ["fc_amount", "rate"],
        calculate: (v) => v.fc_amount * v.rate,
      },
    ],
    deductionFields: [
      {
        name: "acname",
        formName: "acno",
        label: "A/c Name",
        type: "select",
        options: "accounts",
        apiEndpoint: "/api/accounts/acno?macno=001",
        createEndpoint: "/api/accounts/acno",
        nameKey: "acname",
        valueKey: "acno",
        modalFields: [
          { name: "acname", label: "Account Name", type: "text", required: true },
          {
            name: "macno",
            label: "Main Account",
            type: "select",
            options: "mainAccounts",
            apiEndpoint: "/api/accounts/macno",
            valueKey: "macno",
            nameKey: "macname",
            required: true,
          },
        ],
      },
      {
        name: "ccname",
        formName: "ccno",
        label: "Cost Center",
        type: "select",
        options: "costCenters",
        apiEndpoint: "/api/setup/cost_centers",
        createEndpoint: "/api/setup/cost_centers",
        nameKey: "ccname",
        valueKey: "ccno",
        modalFields: [
          { name: "ccname", label: "Cost Center Name", type: "text", required: true },
        ],
      },
      { name: "invoice_no", label: "Invoice No", type: "text" },
      { name: "wht_rate", label: "WHT Rate", type: "number" },
      { name: "chno", label: "Check No", type: "text" },
      { name: "narration1", label: "Narration", type: "text" },
      { name: "narration2", label: "Narration2", type: "text" },
      {
        name: "currency",
        formName: "currency",
        label: "Currency",
        type: "select",
        options: "currencies",
        apiEndpoint: "/api/setup/currencies",
        createEndpoint: "/api/setup/currencies",
        nameKey: "currency",
        valueKey: "id",
        modalFields: [
          { name: "currency", label: "Currency Name", type: "text", required: true },
        ],
      },
      { name: "fc_amount", label: "FC Amt", type: "number" },
      { name: "rate", label: "Exc Rate", type: "number" },
      {
        name: "damt",
        label: "Amount",
        type: "number",
        dependencies: ["fc_amount", "rate"],
        calculate: (v) => v.fc_amount * v.rate,
      },
    ],
    totals: {
      mainTotal: {
        label: "Total Receipts",
        calculate: (lines) => lines.reduce((sum, l) => sum + (l.camt || 0), 0),
      },
      deductionTotal: {
        label: "Total Deductions",
        calculate: (lines) => lines.reduce((sum, l) => sum + (l.damt || 0), 0),
      },
      netTotal: {
        label: "Net Receipt",
        calculate: (_, t) => t.mainTotal - t.deductionTotal,
      },
    },
    balanceCheck: {
      condition: (formData) => formData.totals.netTotal >= 0,
      errorMessage: (formData) =>
        `Net Receipt (${formData.totals.netTotal.toFixed(2)}) cannot be negative.`,
    },
    tableFields: [
      { name: "dateD", label: "Date", type: "date" },
      { name: "tran_id", label: "Transaction No", type: "text" },
      { name: "vr_no", label: "Voucher No", type: "text" },
      { name: "pycd", label: "Received At", type: "text" },
      { name: "rmk", label: "Narration", type: "text" },
    ],
  },
  journal: {
    tran_code: 3,
    hasDeductionBlock: false,
    masterFields: [
      { name: "dateD", label: "Date", type: "date", required: true },
      { name: "vr_no", label: "Vr No", type: "text", required: true, autoGenerate: true },
      { name: "rmk1", label: "Narration", type: "textarea" },
    ],
    lineFields: [
      {
        name: "acname",
        formName: "acno",
        label: "A/c Name",
        type: "select",
        options: "accounts",
        apiEndpoint: "/api/accounts/acno?macno=001",
        createEndpoint: "/api/accounts/acno",
        nameKey: "acname",
        valueKey: "acno",
        modalFields: [
          { name: "acname", label: "Account Name", type: "text", required: true },
          {
            name: "macno",
            label: "Main Account",
            type: "select",
            options: "mainAccounts",
            apiEndpoint: "/api/accounts/macno",
            valueKey: "macno",
            nameKey: "macname",
            required: true,
          },
        ],
      },
      {
        name: "ccname",
        formName: "ccno",
        label: "Cost Center",
        type: "select",
        options: "costCenters",
        apiEndpoint: "/api/setup/cost_centers",
        createEndpoint: "/api/setup/cost_centers",
        nameKey: "ccname",
        valueKey: "ccno",
        modalFields: [
          { name: "ccname", label: "Cost Center Name", type: "text", required: true },
        ],
      },
      { name: "invoice_no", label: "Invoice No", type: "text" },
      { name: "narration1", label: "Narration1", type: "text" },
      { name: "damt", label: "Debit Amount", type: "number" },
      { name: "camt", label: "Credit Amount", type: "number" },
    ],
    totals: {
      debitTotal: {
        label: "Total Debit",
        calculate: (lines) => lines.reduce((sum, l) => sum + (l.damt || 0), 0),
      },
      creditTotal: {
        label: "Total Credit",
        calculate: (lines) => lines.reduce((sum, l) => sum + (l.camt || 0), 0),
      },
    },
    balanceCheck: {
      condition: (formData) => formData.totals.debitTotal === formData.totals.creditTotal,
      errorMessage: (formData) =>
        `Total Debit (${formData.totals.debitTotal.toFixed(2)}) must equal Total Credit (${formData.totals.creditTotal.toFixed(2)}).`,
    },
    tableFields: [
      { name: "dateD", label: "Date", type: "date" },
      { name: "tran_id", label: "Transaction No", type: "text" },
      { name: "vr_no", label: "Voucher No", type: "text" },
      { name: "rmk1", label: "Narration", type: "text" },
    ],
  },
  purchase: {
    tran_code: 4,
    hasDeductionBlock: false,
    masterFields: [
      { name: "dateD", label: "Date", type: "date", required: true },
      { name: "time", label: "Time", type: "time", required: true },
      { name: "vr_no", label: "Vr No", type: "text", required: true, autoGenerate: true },

      {
        name: "pycd",
        label: "Vendor",
        type: "select",
        options: "accounts",
        apiEndpoint: "/api/accounts/acno?macno=001",
        createEndpoint: "/api/accounts/acno",
        nameKey: "acname",
        valueKey: "acno",
        modalFields: [
          { name: "name", label: "Vendor Name", type: "text", required: true },
        ],
      },
      { name: "check_no", label: "ST Inv No", type: "text" },
      { name: "check_date", label: "ST Inv Date", type: "Date" },
      { name: "rmk", label: "Narration", type: "textarea" },
      { name: "rmk3", label: "Prd Cat", type: "text" },
      { name: "invoice_no", label: "Com Inv No", type: "text" },
      {
        name: "godown",
        label: "Godown",
        type: "select",
        options: "godowns",
        apiEndpoint: "/api/setup/godowns",
        createEndpoint: "/api/setup/godowns",
        nameKey: "godown",
        valueKey: "id",
        modalFields: [
          { name: "godown", label: "Godown Name", type: "text", required: true },
        ],
      },
      { name: "rmk2", label: "Delivery No", type: "text" },
      
    ],
    lineFields: [
      {
        name: "acno",
        label: "A/c Name",
        formName: "acno",
        type: "select",
        options: "accounts",
        apiEndpoint: "/api/accounts/acno?macno=001",
        createEndpoint: "/api/accounts/acno",
        nameKey: "acname",
        valueKey: "acno",
        modalFields: [
          { name: "acname", label: "Account Name", type: "text", required: true },
          {
            name: "macno",
            label: "Main Account",
            type: "select",
            options: "mainAccounts",
            apiEndpoint: "/api/accounts/macno",
            valueKey: "macno",
            nameKey: "macname",
            required: true,
          },
        ],
      },
      {
        name: "itcd",
        label: "Product",
        type: "select",
        options: "products",
        apiEndpoint: "/api/setup/items",
        createEndpoint: "/api/setup/items",
        nameKey: "item",
        valueKey: "itcd",
        modalFields: [
          { name: "item", label: "Product Name", type: "text", required: true },
          {
            name: "ic_id",
            label: "Item Category",
            type: "select",
            options: "itemCategories",
            apiEndpoint: "/api/setup/item_categories",
            valueKey: "id",
            nameKey: "ic_name",
            required: true,
          },

        ],
      },
      { name: "no_of_pack", label: "No of Packs", type: "number" },
      { name: "qty_per_pack", label: "Qty Per Pack", type: "number" },
      {
        name: "qty",
        label: "Qty",
        type: "number",
        dependencies: ["no_of_pack", "qty_per_pack"],
        calculate: (v) => v.no_of_pack * v.qty_per_pack,
      },
      { name: "rate", label: "Rate", type: "number" },
      {
        name: "gross_amount",
        label: "Gross Amount",
        type: "number",
        dependencies: ["qty", "rate"],
        calculate: (v) => v.qty * v.rate,
      },
      { name: "st_rate", label: "ST Rate", type: "number" },
      {
        name: "st_amount",
        label: "ST Amount",
        type: "number",
        dependencies: ["gross_amount", "st_rate"],
        calculate: (v) => (v.gross_amount * v.st_rate) / 100,
      },
      { name: "additional_tax", label: "Additional Tax", type: "number" },
      {
        name: "camt",
        label: "Amount",
        type: "number",
        dependencies: ["gross_amount", "st_amount", "additional_tax"],
        calculate: (v) => v.gross_amount + v.st_amount + (v.additional_tax || 0),
      },
    ],
    totals: {
      totalQty: {
        label: "Total Qty",
        calculate: (lines) => lines.reduce((sum, l) => sum + (l.qty || 0), 0),
      },
      grossTotal: {
        label: "Total Gross Amount",
        calculate: (lines) => lines.reduce((sum, l) => sum + (l.gross_amount || 0), 0),
      },
      taxTotal: {
        label: "Total ST Amount",
        calculate: (lines) => lines.reduce((sum, l) => sum + (l.st_amount || 0), 0),
      },
      additionalTaxTotal: {
        label: "Total Additional Tax",
        calculate: (lines) => lines.reduce((sum, l) => sum + (l.additional_tax || 0), 0),
      },
      netTotal: {
        label: "Total Amount",
        calculate: (lines) => lines.reduce((sum, l) => sum + (l.camt || 0), 0),
      },
    },
    tableFields: [
      { name: "dateD", label: "Date", type: "date" },
      { name: "tran_id", label: "Transaction No", type: "text" },
      { name: "vr_no", label: "Voucher No", type: "text" },
      { name: "pycd", label: "Vendor", type: "text" },
      { name: "rmk", label: "Narration", type: "text" },
    ],
  },
  sale: {
    tran_code: 6,
    hasDeductionBlock: false,
    masterFields: [
      { name: "dateD", label: "Date", type: "date", required: true },
      { name: "time", label: "Time", type: "time", required: true },
      { name: "vr_no", label: "Vr No", type: "text", required: true, autoGenerate: true },

      {
        name: "pycd",
        label: "Customer",
        type: "select",
        options: "accounts",
        apiEndpoint: "/api/accounts/acno?macno=001",
        createEndpoint: "/api/accounts/acno",
        nameKey: "acname",
        valueKey: "acno",
        modalFields: [
          { name: "name", label: "Customer Name", type: "text", required: true },
        ],
      },
      { name: "check_no", label: "ST Inv No", type: "text" },
      { name: "check_date", label: "ST Inv Date", type: "Date" },
      { name: "rmk", label: "Narration", type: "textarea" },
      { name: "rmk3", label: "Prd Cat", type: "text" },
      { name: "invoice_no", label: "Com Inv No", type: "text" },
      {
        name: "godown",
        label: "Godown",
        type: "select",
        options: "godowns",
        apiEndpoint: "/api/setup/godowns",
        createEndpoint: "/api/setup/godowns",
        nameKey: "godown",
        valueKey: "id",
        modalFields: [
          { name: "godown", label: "Godown Name", type: "text", required: true },
        ],
      },
      { name: "rmk2", label: "Delivery No", type: "text" },
      
    ],
    lineFields: [
      {
        name: "acno",
        label: "A/c Name",
        type: "select",
        options: "accounts",
        apiEndpoint: "/api/accounts/acno?macno=001",
        createEndpoint: "/api/accounts/acno",
        nameKey: "acname",
        valueKey: "acno",
        modalFields: [
          { name: "acname", label: "Account Name", type: "text", required: true },
          {
            name: "macno",
            label: "Main Account",
            type: "select",
            options: "mainAccounts",
            apiEndpoint: "/api/accounts/macno",
            valueKey: "macno",
            nameKey: "macname",
            required: true,
          },
        ],
      },
      {
        name: "itcd",
        label: "Product",
        type: "select",
        options: "products",
        apiEndpoint: "/api/setup/items",
        createEndpoint: "/api/setup/items",
        nameKey: "item",
        valueKey: "itcd",
        modalFields: [
          { name: "item", label: "Product Name", type: "text", required: true },
          {
            name: "ic_id",
            label: "Item Category",
            type: "select",
            options: "itemCategories",
            apiEndpoint: "/api/setup/item_categories",
            valueKey: "id",
            nameKey: "ic_name",
            required: true,
          },
        ],
      },
      { name: "no_of_pack", label: "No of Packs", type: "number" },
      { name: "qty_per_pack", label: "Qty Per Pack", type: "number" },
      {
        name: "qty",
        label: "Qty",
        type: "number",
        dependencies: ["no_of_pack", "qty_per_pack"],
        calculate: (v) => v.no_of_pack * v.qty_per_pack,
      },
      { name: "rate", label: "Rate", type: "number" },
      {
        name: "gross_amount",
        label: "Gross Amount",
        type: "number",
        dependencies: ["qty", "rate"],
        calculate: (v) => v.qty * v.rate,
      },
      { name: "st_rate", label: "ST Rate", type: "number" },
      {
        name: "st_amount",
        label: "ST Amount",
        type: "number",
        dependencies: ["gross_amount", "st_rate"],
        calculate: (v) => (v.gross_amount * v.st_rate) / 100,
      },
      { name: "additional_tax", label: "Additional Tax", type: "number" },
      {
        name: "damt",
        label: "Amount",
        type: "number",
        dependencies: ["gross_amount", "st_amount", "additional_tax"],
        calculate: (v) => v.gross_amount + v.st_amount + (v.additional_tax || 0),
      },
    ],
    totals: {
      totalQty: {
        label: "Total Qty",
        calculate: (lines) => lines.reduce((sum, l) => sum + (l.qty || 0), 0),
      },
      grossTotal: {
        label: "Total Gross Amount",
        calculate: (lines) => lines.reduce((sum, l) => sum + (l.gross_amount || 0), 0),
      },
      taxTotal: {
        label: "Total ST Amount",
        calculate: (lines) => lines.reduce((sum, l) => sum + (l.st_amount || 0), 0),
      },
      additionalTaxTotal: {
        label: "Total Additional Tax",
        calculate: (lines) => lines.reduce((sum, l) => sum + (l.additional_tax || 0), 0),
      },
      netTotal: {
        label: "Total Amount",
        calculate: (lines) => lines.reduce((sum, l) => sum + (l.damt || 0), 0),
      },
    },
    tableFields: [
      { name: "dateD", label: "Date", type: "date" },
      { name: "tran_id", label: "Transaction No", type: "text" },
      { name: "vr_no", label: "Voucher No", type: "text" },
      { name: "pycd", label: "Customer", type: "text" },
      { name: "rmk", label: "Narration", type: "text" },
    ],
  },
  purchaseReturn: {
    tran_code: 9,
    hasDeductionBlock: false,
    masterFields: [
      { name: "dateD", label: "Date", type: "date", required: true },
      { name: "time", label: "Time", type: "time", required: true },
      { name: "vr_no", label: "Vr No", type: "text", required: true, autoGenerate: true },

      {
        name: "pycd",
        label: "Vendor",
        type: "select",
        options: "accounts",
        apiEndpoint: "/api/accounts/acno?macno=001",
        createEndpoint: "/api/accounts/acno",
        nameKey: "acname",
        valueKey: "acno",
        modalFields: [
          { name: "name", label: "Vendor Name", type: "text", required: true },
        ],
      },
      { name: "check_no", label: "ST Inv No", type: "text" },
      { name: "check_date", label: "ST Inv Date", type: "Date" },
      { name: "rmk", label: "Narration", type: "textarea" },
      { name: "rmk3", label: "Prd Cat", type: "text" },
      { name: "invoice_no", label: "Com Inv No", type: "text" },
      {
        name: "godown",
        label: "Godown",
        type: "select",
        options: "godowns",
        apiEndpoint: "/api/setup/godowns",
        createEndpoint: "/api/setup/godowns",
        nameKey: "godown",
        valueKey: "id",
        modalFields: [
          { name: "godown", label: "Godown Name", type: "text", required: true },
        ],
      },
      { name: "rmk2", label: "Delivery No", type: "text" },
      
    ],
    lineFields: [
      {
        name: "acno",
        label: "A/c Name",
        formName: "acno",
        type: "select",
        options: "accounts",
        apiEndpoint: "/api/accounts/acno?macno=001",
        createEndpoint: "/api/accounts/acno",
        nameKey: "acname",
        valueKey: "acno",
        modalFields: [
          { name: "acname", label: "Account Name", type: "text", required: true },
          {
            name: "macno",
            label: "Main Account",
            type: "select",
            options: "mainAccounts",
            apiEndpoint: "/api/accounts/macno",
            valueKey: "macno",
            nameKey: "macname",
            required: true,
          },
        ],
      },
      {
        name: "itcd",
        label: "Product",
        type: "select",
        options: "products",
        apiEndpoint: "/api/setup/items",
        createEndpoint: "/api/setup/items",
        nameKey: "item",
        valueKey: "itcd",
        modalFields: [
          { name: "item", label: "Product Name", type: "text", required: true },
          {
            name: "ic_id",
            label: "Item Category",
            type: "select",
            options: "itemCategories",
            apiEndpoint: "/api/setup/item_categories",
            valueKey: "id",
            nameKey: "ic_name",
            required: true,
          },

        ],
      },
      { name: "no_of_pack", label: "No of Packs", type: "number" },
      { name: "qty_per_pack", label: "Qty Per Pack", type: "number" },
      {
        name: "qty",
        label: "Qty",
        type: "number",
        dependencies: ["no_of_pack", "qty_per_pack"],
        calculate: (v) => v.no_of_pack * v.qty_per_pack,
      },
      { name: "rate", label: "Rate", type: "number" },
      {
        name: "gross_amount",
        label: "Gross Amount",
        type: "number",
        dependencies: ["qty", "rate"],
        calculate: (v) => v.qty * v.rate,
      },
      { name: "st_rate", label: "ST Rate", type: "number" },
      {
        name: "st_amount",
        label: "ST Amount",
        type: "number",
        dependencies: ["gross_amount", "st_rate"],
        calculate: (v) => (v.gross_amount * v.st_rate) / 100,
      },
      { name: "additional_tax", label: "Additional Tax", type: "number" },
      {
        name: "camt",
        label: "Amount",
        type: "number",
        dependencies: ["gross_amount", "st_amount", "additional_tax"],
        calculate: (v) => v.gross_amount + v.st_amount + (v.additional_tax || 0),
      },
    ],
    totals: {
      totalQty: {
        label: "Total Qty",
        calculate: (lines) => lines.reduce((sum, l) => sum + (l.qty || 0), 0),
      },
      grossTotal: {
        label: "Total Gross Amount",
        calculate: (lines) => lines.reduce((sum, l) => sum + (l.gross_amount || 0), 0),
      },
      taxTotal: {
        label: "Total ST Amount",
        calculate: (lines) => lines.reduce((sum, l) => sum + (l.st_amount || 0), 0),
      },
      additionalTaxTotal: {
        label: "Total Additional Tax",
        calculate: (lines) => lines.reduce((sum, l) => sum + (l.additional_tax || 0), 0),
      },
      netTotal: {
        label: "Total Amount",
        calculate: (lines) => lines.reduce((sum, l) => sum + (l.camt || 0), 0),
      },
    },
    tableFields: [
      { name: "dateD", label: "Date", type: "date" },
      { name: "tran_id", label: "Transaction No", type: "text" },
      { name: "vr_no", label: "Voucher No", type: "text" },
      { name: "pycd", label: "Vendor", type: "text" },
      { name: "rmk", label: "Narration", type: "text" },
    ],
  },
  saleReturn: {
    tran_code: 10,
    hasDeductionBlock: false,
    masterFields: [
      { name: "dateD", label: "Date", type: "date", required: true },
      { name: "time", label: "Time", type: "time", required: true },
      { name: "vr_no", label: "Vr No", type: "text", required: true, autoGenerate: true },

      {
        name: "pycd",
        label: "Vendor",
        type: "select",
        options: "accounts",
        apiEndpoint: "/api/accounts/acno?macno=001",
        createEndpoint: "/api/accounts/acno",
        nameKey: "acname",
        valueKey: "acno",
        modalFields: [
          { name: "name", label: "Vendor Name", type: "text", required: true },
        ],
      },
      { name: "check_no", label: "ST Inv No", type: "text" },
      { name: "check_date", label: "ST Inv Date", type: "Date" },
      { name: "rmk", label: "Narration", type: "textarea" },
      { name: "rmk3", label: "Prd Cat", type: "text" },
      { name: "invoice_no", label: "Com Inv No", type: "text" },
      {
        name: "godown",
        label: "Godown",
        type: "select",
        options: "godowns",
        apiEndpoint: "/api/setup/godowns",
        createEndpoint: "/api/setup/godowns",
        nameKey: "godown",
        valueKey: "id",
        modalFields: [
          { name: "godown", label: "Godown Name", type: "text", required: true },
        ],
      },
      { name: "rmk2", label: "Delivery No", type: "text" },
      
    ],
    lineFields: [
      {
        name: "acno",
        label: "A/c Name",
        formName: "acno",
        type: "select",
        options: "accounts",
        apiEndpoint: "/api/accounts/acno?macno=001",
        createEndpoint: "/api/accounts/acno",
        nameKey: "acname",
        valueKey: "acno",
        modalFields: [
          { name: "acname", label: "Account Name", type: "text", required: true },
          {
            name: "macno",
            label: "Main Account",
            type: "select",
            options: "mainAccounts",
            apiEndpoint: "/api/accounts/macno",
            valueKey: "macno",
            nameKey: "macname",
            required: true,
          },
        ],
      },
      {
        name: "itcd",
        label: "Product",
        type: "select",
        options: "products",
        apiEndpoint: "/api/setup/items",
        createEndpoint: "/api/setup/items",
        nameKey: "item",
        valueKey: "itcd",
        modalFields: [
          { name: "item", label: "Product Name", type: "text", required: true },
          {
            name: "ic_id",
            label: "Item Category",
            type: "select",
            options: "itemCategories",
            apiEndpoint: "/api/setup/item_categories",
            valueKey: "id",
            nameKey: "ic_name",
            required: true,
          },

        ],
      },
      { name: "no_of_pack", label: "No of Packs", type: "number" },
      { name: "qty_per_pack", label: "Qty Per Pack", type: "number" },
      {
        name: "qty",
        label: "Qty",
        type: "number",
        dependencies: ["no_of_pack", "qty_per_pack"],
        calculate: (v) => v.no_of_pack * v.qty_per_pack,
      },
      { name: "rate", label: "Rate", type: "number" },
      {
        name: "gross_amount",
        label: "Gross Amount",
        type: "number",
        dependencies: ["qty", "rate"],
        calculate: (v) => v.qty * v.rate,
      },
      { name: "st_rate", label: "ST Rate", type: "number" },
      {
        name: "st_amount",
        label: "ST Amount",
        type: "number",
        dependencies: ["gross_amount", "st_rate"],
        calculate: (v) => (v.gross_amount * v.st_rate) / 100,
      },
      { name: "additional_tax", label: "Additional Tax", type: "number" },
      {
        name: "damt",
        label: "Amount",
        type: "number",
        dependencies: ["gross_amount", "st_amount", "additional_tax"],
        calculate: (v) => v.gross_amount + v.st_amount + (v.additional_tax || 0),
      },
    ],
    totals: {
      totalQty: {
        label: "Total Qty",
        calculate: (lines) => lines.reduce((sum, l) => sum + (l.qty || 0), 0),
      },
      grossTotal: {
        label: "Total Gross Amount",
        calculate: (lines) => lines.reduce((sum, l) => sum + (l.gross_amount || 0), 0),
      },
      taxTotal: {
        label: "Total ST Amount",
        calculate: (lines) => lines.reduce((sum, l) => sum + (l.st_amount || 0), 0),
      },
      additionalTaxTotal: {
        label: "Total Additional Tax",
        calculate: (lines) => lines.reduce((sum, l) => sum + (l.additional_tax || 0), 0),
      },
      netTotal: {
        label: "Total Amount",
        calculate: (lines) => lines.reduce((sum, l) => sum + (l.camt || 0), 0),
      },
    },
    tableFields: [
      { name: "dateD", label: "Date", type: "date" },
      { name: "tran_id", label: "Transaction No", type: "text" },
      { name: "vr_no", label: "Voucher No", type: "text" },
      { name: "pycd", label: "Vendor", type: "text" },
      { name: "rmk", label: "Narration", type: "text" },
    ],
  },
}      