name: Deploy to VPS

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to GitHub Container Registry
        run: echo "${{ secrets.GHCR_TOKEN }}" | docker login ghcr.io -u ${{ secrets.GHCR_USERNAME }} --password-stdin

      - name: Build Docker image
        run: |
          docker build --no-cache . -t ghcr.io/${{ secrets.GHCR_USERNAME }}/novapos:latest --platform linux/amd64

      - name: Push Docker image to GHCR
        run: |
          docker push ghcr.io/${{ secrets.GHCR_USERNAME }}/novapos:latest

      - name: Deploy to VPS via SSH
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          password: ${{ secrets.VPS_PASSWORD }}
          port: 2746
          script: |
            cd accounting
            echo "${{ secrets.GHCR_TOKEN }}" | docker login ghcr.io -u ${{ secrets.GHCR_USERNAME }} --password-stdin
            docker stop novapos || true
            docker rm novapos || true
            docker image rm ghcr.io/${{ secrets.GHCR_USERNAME }}/novapos:latest || true
            docker pull ghcr.io/${{ secrets.GHCR_USERNAME }}/novapos:latest
            docker run -d --env-file .env -p 3003:3003 -v /var/www/uploads:/app/public/uploads --name accounting ghcr.io/${{ secrets.GHCR_USERNAME }}/accounting:latest
